=== AulaPlanetaColombia/Matematicas/fuentes/visuales/grado11/guion05/guionAbierto/MA_11_05_CO_cuaderno/cuadernoestudio/dtd/libro.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ENTITY % xhtmltbls SYSTEM "xhtml-tbl.dtd" >
%xhtmltbls;


<!ELEMENT libro ( libroTitulo, libroEntradilla?, seccion1+, masinformacion ) >

<!ATTLIST libro
	id ID #REQUIRED 
	cultura (es-ES | en-GB) "es-ES" 
	tipoUnidad (cero | final | normal) "normal" >
	
<!ELEMENT libroTitulo ( #PCDATA ) >

<!ELEMENT libroEntradilla ( p+ )  >

<!--************************************************************
             TEXTO, PARRAFO, LISTAS, ENLACES
**************************************************************-->

<!ELEMENT p ( #PCDATA | br | cursiva | enlace | negrita | negritacursiva | subindice | superindice )* >

<!ATTLIST p
	centrado (si) #IMPLIED >

<!ELEMENT br EMPTY >

<!ELEMENT blockquote ( p+ ) >

<!ELEMENT listaNumerada ( listaElemento+ ) >

<!ELEMENT listaSinNumerar ( listaElemento+ ) >

<!ELEMENT listaElemento ( #PCDATA | br | enlace | negrita | cursiva | formula | imagen | listaNumerada | listaSinNumerar | negritacursiva | p | subindice | superindice )*  >

<!ELEMENT cursiva ( #PCDATA | negrita | subindice | superindice)* >

<!ELEMENT negrita ( #PCDATA | cursiva | subindice | superindice)* >

<!ELEMENT negritacursiva ( #PCDATA | subindice | superindice)* >

<!ELEMENT subindice ( #PCDATA | cursiva | negrita | negritacursiva )* >

<!ELEMENT superindice ( #PCDATA | cursiva | negrita | negritacursiva)* >

<!ELEMENT enlace ( #PCDATA | br |negrita | cursiva | negritacursiva | subindice | superindice)* >

<!ATTLIST enlace
		destino CDATA #REQUIRED >


<!--************************************************************
                FORMULAS E IMAGENES
**************************************************************-->

<!ELEMENT formula ( p* ) >

<!ATTLIST formula
		src CDATA #REQUIRED
		alineacion (izquierda | centrada) "izquierda"
			>

<!ELEMENT imagen ( p | listaNumerada | listaSinNumerar )* >

<!ATTLIST imagen
		src CDATA #REQUIRED
		ampliable (no) #IMPLIED
		imprimir-grande (si) #IMPLIED 
		>


<!--************************************************************
                SECCIONES
**************************************************************-->

<!ELEMENT seccion1 ( seccion1Titulo, seccion1Texto ) >

<!ATTLIST seccion1
		id CDATA #IMPLIED
		mostrarautonomico (si|no) #IMPLIED>

<!ELEMENT seccion1Texto (( blockquote | destacado | destacadoConImagen | formula | imagen | listaNumerada | listaSinNumerar | media | nota | p | practica | profundiza | recuerda | table)*, seccion2*) >

<!ELEMENT seccion1Titulo ( #PCDATA | cursiva | subindice | superindice )* >

<!ELEMENT seccion2 ( seccion2Titulo, seccion2Texto ) >

<!ATTLIST seccion2
		id CDATA #IMPLIED >

<!ELEMENT seccion2Texto (( blockquote | destacado | destacadoConImagen | formula | imagen | listaNumerada | listaSinNumerar | media | nota | p | practica | profundiza | recuerda | table)*, seccion3*) >

<!ELEMENT seccion2Titulo ( #PCDATA | cursiva | subindice | superindice )* >

<!ELEMENT seccion3 ( seccion3Titulo, seccion3Texto ) >

<!ATTLIST seccion3
		id CDATA #IMPLIED >

<!ELEMENT seccion3Texto ( blockquote | destacado | destacadoConImagen | formula | imagen | listaNumerada | listaSinNumerar | media | nota | p | practica | profundiza | recuerda | table )* >

<!ELEMENT seccion3Titulo ( #PCDATA | cursiva | subindice | superindice )* >

<!--************************************************************
                OTROS
**************************************************************-->

<!ELEMENT masinformacion ( mapaconceptual, autoevaluate, enlacesreferencia ) >

<!ATTLIST masinformacion
		id CDATA #IMPLIED >

<!ELEMENT autoevaluate ( enlace ) >

<!ELEMENT destacado ( destacadoTitulo, destacadoTexto ) >

<!ATTLIST destacado

	clip (no) #IMPLIED	>

<!ELEMENT destacadoTexto ( p | formula | imagen | listaNumerada | listaSinNumerar )+ >

<!ELEMENT destacadoTitulo ( #PCDATA | cursiva | subindice | superindice )* >


<!ELEMENT destacadoConImagen ( destacadoConImagenTitulo, destacadoConImagenTexto ) >

<!ATTLIST destacadoConImagen
	mostrarautonomico (si|no) #IMPLIED		
>
	
<!ELEMENT destacadoConImagenTexto ( p | formula | imagen | listaNumerada | listaSinNumerar )+ >

<!ELEMENT destacadoConImagenTitulo ( #PCDATA | cursiva | subindice | superindice )* >

<!ELEMENT enlacesreferencia ( enlace+ ) >

<!ELEMENT mapaconceptual ( enlace ) >

<!ELEMENT practica ( enlace+ ) >

<!ELEMENT profundiza ( (enlace, no-imprimible?)+ ) > 

<!ELEMENT no-imprimible EMPTY >

<!ELEMENT recuerda ( recuerdaTexto ) >

<!ELEMENT recuerdaTexto ( p | formula | imagen | listaNumerada | listaSinNumerar )+ >

<!ELEMENT media ( enlace+ ) >

<!ELEMENT nota ( p+ ) >


<!--************************************************************
                       TABLE
**************************************************************

<!ELEMENT table ( caption?, tr+ ) >

<!ELEMENT caption ( #PCDATA | br | negrita | cursiva | negritaCursiva | subindice | superindice )* >

<!ELEMENT tr ( td+ ) >

<!ELEMENT td ( #PCDATA | br | negrita | cursiva | listaNumerada | listaSinNumerar | negritaCursiva | p | subindice | superindice )* >

<!ATTLIST td 
	colspan (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12) #IMPLIED 
	rowspan (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12) #IMPLIED>-->

=== AulaPlanetaColombia/Matematicas/fuentes/visuales/grado09/guion13/guionAbierto/MA_09_13_CO_cuaderno/cuadernoestudio.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="cuadernoestudio/dtd/libro.xslt" type="text/xsl"?>
<!--Arbortext, Inc., 1988-2015, v.4002-->
<!DOCTYPE libro SYSTEM "cuadernoestudio/dtd/libro.dtd">
<?Pub Inc?>
<libro id="MA_09_13_CO">
<libroTitulo>La probabilidad</libroTitulo>
<seccion1 id="S1_MA_09_13_CO_54A20C78686940AEA846928D458155DC">
<seccion1Titulo>Los experimentos aleatorios</seccion1Titulo>
<seccion1Texto>
<p>Se denominan <negrita>experimentos aleatorios</negrita> aquellas
situaciones en las que no se puede determinar o predecir el resultado,
ya que éste depende solamente del azar.  Extraer de una baraja de
naipes una carta, lanzar un dado o una moneda al aire, son algunos
ejemplos de experimentos aleatorios ya que no se puede determinar
anticipadamente el resultado que se va a obtener.</p>
<p>La <negrita>probabilidad</negrita> es una rama de las matemáticas
que estudia cuantitativamente la posibilidad que un hecho ocurra o
no. </p>
<imagen src="MA_09_13_CO_IMG01_small.png">
<p>La ruleta es un juego de azar, que consiste en lanzar una bola
a la ruleta, mientras ésta gira. También es considerada un experimento
aleatorio, pues el azar determina en que casilla de la ruleta va a
caer la bola.</p>
</imagen>
<seccion2 id="S2_MA_09_13_CO_686DEEB17CC7453D97F70236BCC794EE">
<seccion2Titulo>El espacio muestral</seccion2Titulo>
<seccion2Texto>
<p>El <negrita>espacio muestral</negrita> es el conjunto de <negrita
>todos</negrita> los posibles resultados que se pueden obtener de
un experimento aleatorio. Generalmente, los espacios muestrales se
denotan con la letra <negritacursiva>S</negritacursiva>.</p>
<p>Los siguientes son ejemplos de espacios muestrales de algunos experimentos
aleatorios:</p>
<imagen src="MA_09_13_CO_IMG02_small.png">
<p>Al lanzar una moneda al aire y anotar sus resultados, dado que
c: cara, s: sello. El espacio muestral es <cursiva>S</cursiva> = {c,
s}</p>
</imagen>
<listaSinNumerar>
<listaElemento>El lanzamiento de un dado al aire, tiene como espacio
muestral: <cursiva>S</cursiva> = {1, 2, 3, 4, 5, 6}</listaElemento>
<listaElemento>El espacio muestral de lanzar un dado y una moneda
al aire dado que c representa cara y s sello es <cursiva>S</cursiva
> = {(c, 1); (c, 2); (c, 3); (c, 4); (c, 5); (c, 6); (s, 1); (s ,2);
(s, 3); (s, 4); (s, 5); (s, 6)}</listaElemento>
<listaElemento>Entre Jorge, María, Diana, Cristian y Andres seleccionar
una persona al azar como ganadora de una rifa <cursiva>S</cursiva
> = {Jorge, María, Diana, Cristian y Andrés}</listaElemento>
</listaSinNumerar>
</seccion2Texto></seccion2><seccion2
id="S2_MA_09_13_CO_686DEEB17CC7453D97F70236BCC772CC">
<seccion2Titulo>El suceso aleatorio</seccion2Titulo>
<seccion2Texto>
<p>Los <negrita>sucesos</negrita> son los posibles resultados de un
experimento aleatorio. En general se define como:</p>
<destacado><destacadoTitulo>Suceso aleatorio</destacadoTitulo>
<destacadoTexto>
<p>Un subconjunto del espacio muestral se denomina <negrita>suceso</negrita
> y se denota con letras mayúsculas como <cursiva>A</cursiva>, <cursiva
>B</cursiva>, <cursiva>C</cursiva>.</p>
</destacadoTexto></destacado>
<p>Algunos <negrita>sucesos</negrita> que se pueden determinar al
lanzar un dado son: obtener un número impar, obtener un número menor
a 3, sacar el número 4, entre otros.</p>
<p>Por ejemplo, dado el experimento aleatorio de lanzar al aire un
dado y anotar el resultado, tiene como espacio muestral al conjunto <cursiva
>S</cursiva> = {1, 2, 3, 4, 5, 6}.</p>
<listaSinNumerar>
<listaElemento>Sea <cursiva>A</cursiva> el suceso de obtener un número
impar, por lo tanto <cursiva>A</cursiva> = {1, 3, 5}.</listaElemento>
<listaElemento>Sea <cursiva>B</cursiva> el suceso de obtener un número
menor que 3, así <cursiva>B</cursiva> = {1, 2, 3}.</listaElemento>
<listaElemento>Sea <cursiva>C</cursiva> el suceso de obtener 4, de
esta manera <cursiva>C</cursiva> = {4}.</listaElemento>
</listaSinNumerar>
<p>Un suceso aleatorio se clasifica en suceso elemental o simple,
suceso compuesto, suceso seguro y suceso imposible como se muestra
en la siguiente tabla:</p>
<table border="1"><colgroup><col/><col/><col/></colgroup>
<tbody>
<tr>
<td align="center"><negrita>Tipos de sucesos</negrita></td>
<td align="center"><negrita>Definición</negrita></td>
<td align="center"><negrita>Ejemplo:</negrita></td>
</tr>
<tr>
<td><negrita>Suceso elemental o simple</negrita></td>
<td>Es aquel suceso conformado por un elemento del espacio muestral. </td>
<td><cursiva>A</cursiva>: obtener el número 3 al lanzar el dado<br
/><cursiva>A</cursiva> = {3}</td>
</tr>
<tr>
<td><negrita>Suceso compuesto</negrita></td>
<td>Es un subconjunto del espacio muestral que está conformado por
dos o más elementos de este.</td>
<td><cursiva>B</cursiva>: obtener un número par al lanzar un dado<br
/><cursiva>B</cursiva> = {2, 4, 6}</td>
</tr>
<tr>
<td><negrita>Suceso seguro</negrita></td>
<td>Está formado por todos los posibles resultados del espacio muestral.</td>
<td><cursiva>C</cursiva>: obtener un número menor que 7 al lanzar
el dado.<br/><cursiva>C</cursiva> = {1, 2, 3, 4, 5, 6} = <cursiva
>S</cursiva></td>
</tr>
<tr>
<td><negrita>Suceso imposible</negrita></td>
<td>Es aquel que no tiene posibilidad de ocurrencia, es decir, es
el subconjunto vacío del espacio muestral.</td>
<td><cursiva>D</cursiva>: obtener cara al lanzar un dado<br/><cursiva
>D</cursiva> = ∅</td>
</tr>
</tbody>
</table>
</seccion2Texto></seccion2><seccion2
id="S2_MA_09_13_CO_686DEEB17CC7453D97F70236BCC738FF">
<seccion2Titulo>Las operaciones con sucesos</seccion2Titulo>
<seccion2Texto>
<p>Dado que los sucesos aleatorios son subconjuntos del espacio muestral,
sobre ellos se pueden definir las operaciones de unión, intersección,
diferencia y complemento entre conjuntos. Así:</p>
<listaSinNumerar>
<listaElemento><negrita>Unión entre sucesos aleatorios:</negrita> dados
los sucesos aleatorios <cursiva>A</cursiva> y <cursiva>B</cursiva
>, la unión <negrita><cursiva>A</cursiva> ⋃ <cursiva>B</cursiva></negrita
> se define como el conjunto de todos los elementos de <cursiva>A</cursiva
>, de <cursiva>B</cursiva> o ambos.</listaElemento>
</listaSinNumerar>
<p>Por ejemplo, observa la siguiente ruleta</p>
<imagen src="MA_09_13_CO_IMG06_small.jpg">
<p>Al hacer girar la ruleta una vez y anotar el número de puntos obtenidos
tiene como espacio muestral<br/><cursiva>S</cursiva> = {1, 2, 3, 4,
5, 6, 7, 8, 9}.</p>
</imagen>
<p>Se consideran los siguientes eventos:</p>
<p><cursiva>A</cursiva>: obtener un múltiplo de 3 en la ruleta.<br
/><cursiva>B</cursiva>: obtener un mayor que 5.</p>
<p>Para determinar <cursiva>A</cursiva> ⋃ <cursiva>B</cursiva>, primero
se determinan los sucesos aleatorios <cursiva>A</cursiva> y <cursiva
>B</cursiva><br/><cursiva>A</cursiva> = {3, 6, 9}<br/><cursiva>B</cursiva
> = {6, 7, 8, 9}</p>
<listaSinNumerar>
<listaElemento><negrita>Intersección entre sucesos aleatorios:</negrita
> dados dos sucesos aleatorios, la intersección <cursiva>A</cursiva
> ⋂ <cursiva>B</cursiva> se define el conjunto de elementos que pertenecen
a ambos conjuntos.</listaElemento>
</listaSinNumerar>
<p>En el ejemplo de la ruleta, cuyo espacio muestral es <cursiva>S</cursiva
> = {1, 2, 3, 4, 5, 6, 7, 8, 9} y sus eventos son:</p>
<p><cursiva>A</cursiva>: obtener un múltiplo de 3 en la ruleta.<br
/><cursiva>B</cursiva>: obtener un mayor que 5.</p>
<p>Dado que,<br/><cursiva>A</cursiva> = {3, 6, 9}<br/><cursiva>B</cursiva
> = {6, 7, 8, 9}</p>
<p>Se obtiene la intersección <cursiva>A</cursiva> ⋂ <cursiva>B</cursiva
> = {6, 9}.</p>
<p>De acuerdo con la intersección entre conjuntos, si los sucesos
aleatorios tienen el mismo espacio muestral, se clasifican en compatibles
o incompatibles.</p>
<table border="1"><colgroup><col/><col/><col/></colgroup>
<tbody>
<tr>
<td align="center"><negrita>Tipos de sucesos</negrita></td>
<td align="center"><negrita>Definición</negrita></td>
<td align="center"><negrita>Ejemplo:</negrita></td>
</tr>
<tr>
<td><negrita>Sucesos compatibles</negrita></td>
<td>Dos sucesos aleatorios son compatibles si su intersección tiene
uno o más elementos del espacio muestral.</td>
<td>Al lanzar un dado al aire y anotar su resultado, los sucesos son<br
/><br/><cursiva>A</cursiva>: obtener un múltiplo de 3.<br/><cursiva
>B</cursiva>: obtener un número impar<br/><br/>Por lo tanto<br/><cursiva
>A</cursiva> = {3, 6}<br/><cursiva>B</cursiva> = {1, 3, 5}<br/><br
/>Los sucesos <cursiva>A</cursiva> y <cursiva>B</cursiva> son compatibles,
puesto que <negrita>su intersección no es vacía</negrita>.<br/><cursiva
>A</cursiva> ⋂ <cursiva>B</cursiva> = {3}</td>
</tr>
<tr>
<td><negrita>Sucesos incompatibles</negrita></td>
<td>Dos sucesos aleatorios son incompatibles si la intersección entre
los sucesos es vacía.</td>
<td>Al lanzar un dado al aire y anotar su resultado, los sucesos son<br
/><br/><cursiva>C</cursiva>: obtener 5 al lanzar el dado<br/><cursiva
>D</cursiva>: obtener un número par<br/><br/>Así<br/><cursiva>C</cursiva
> = {5}<br/><cursiva>D</cursiva> = {2, 4, 6}<br/><br/>Los sucesos <cursiva
>C</cursiva> y <cursiva>D</cursiva> son incompatibles, puesto que
la intersección es vacía<br/><cursiva>C</cursiva> ⋂ <cursiva>D</cursiva
> = ∅</td>
</tr>
</tbody>
</table>
<p><negrita>Suceso contrario:</negrita> dado un suceso aleatorio <cursiva
>A</cursiva> el suceso contrario de <cursiva>A</cursiva> que se denota
como <cursiva>A<superindice>C</superindice></cursiva> se define como
el conjunto de elementos del espacio muestral que no pertenecen al
conjunto <cursiva>A</cursiva></p>
<p>En el ejemplo de la ruleta <cursiva>A<superindice>C</superindice
></cursiva> = {1, 2, 4, 5, 7, 8} y <cursiva>B<superindice>C</superindice
></cursiva> = {1, 2, 3, 4, 5}</p>
<p>Diferencia entre sucesos aleatorios: dados dos sucesos aleatorios <cursiva
